### ISSUE TITLE
Automate github.io release process

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-ios#1117]

**Comment by sima-zhu** [comment]
Is the automation still needed? Could you elaborate the situation on this?

**Comment by tjprescott** [comment]
Yes, this automation would still be needed. We currently have to run a manual process to publish docs, as described here: https://github.com/Azure/azure-sdk-for-ios/wiki/Publishing-Jazzy-Docs-to-GitHub.io

And this process is already being reworked because it does not work for partner teams whose source is not in this repo.

**Comment by kurtzeborn** [comment]
This is a gap we know about.  We should either create a new issue or reopen this one when/if we start working on iOS packages again and need this.

**Comment by tjprescott** [comment]
@kurtzeborn why would we close this issue if we know that this is a gap? We have partner teams asking us right now why we can't automate this process because of the lag that happens when they have to ask us to manually regenerate the docs for them. What purpose does opening a new issue serve?
