### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RodrigoGularte** [Azure/azure-sdk-for-ios#1834]
I added the Azure SDK for iOS at the XCode Version 15.4 (15F31d), through menu File > Add Package Dependencies... and informed the Github URL.
After selecting the basic options and added my project as a target I got the error saying: "the package manifest at '/Package.swift' cannot be accessed (/Package.swift doesn't exist in file system) in https://github.com/Azure/azure-sdk-for-ios
".
I continued anyway, but the SDK is not working. Could you please share some thoughts?

Thanks in advance!

Rodrigo Gularte

**Comment by lucianopa-msft** [comment]
Hi @RodrigoGularte
Unfortunately we do not support Swift Package Manager for our SDK because of limitations that we have.
See the documentation section for detailed information [QuickStart: Add 1:1 video calling to your app
](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-video-calling?pivots=platform-ios#using-xcframework-directly).
