### ISSUE TITLE
Refactor pipeline to remove OnErrorCompletionHandler

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-ios#357]
This method is called if either on(request:...) or on(response:...) returns an error as a way to hopefully handle the error and avoid a failure scenario. So you could handle that logic in those respective methods, and if the logic is different that would certainly make sense. Currently, logging policy is the only policy we have that actually uses this method, so perhaps it would make sense to do away with it.

**Comment by tjprescott** [comment]
Here's the rough structure of the `PipelineStage.process` method:
```Swift
        on(request: pipelineRequest) { request, error in
            if let error = error {
                let pipelineResponse = ...
                // short-circuit and return failure early if error can't be handled
                self.on(error: error, pipelineResponse: pipelineResponse) { _, handled in
                    if !handled {
                        completionHandler(.failure(error), nil)
                        return
                    }
                }
            }
            self.next!.process(request: request) { result, httpResponse in
                switch result {
                case let .success(pipelineResponse):
                    self.on(response: pipelineResponse) { response, error in
                        if let error = error {
                            self.on(error: error, pipelineResponse: pipelineResponse) { _, handled in
                                if !handled {
                                    completionHandler(.failure(error), httpResponse)
                                    return
                                }
                            }
                        }
                        completionHandler(.success(response), httpResponse)
                    }
                case let .failure(error):
                    let pipelineResponse = PipelineResponse(
                        request: request.httpRequest,
                        response: httpResponse,
                        logger: request.logger,
                        context: request.context
                    )
                    self.on(error: error, pipelineResponse: pipelineResponse) { _, handled in
                        if !handled {
                            completionHandler(.failure(error), httpResponse)
                            return
                        }
                    }
                }
            }
```

Looking at this, the purpose of `on(error:...)` is to try and recover from an error in the on request/response methods. `process` is a template method that I don't think we want individual pipeline stages modifying (the only reason it isn't private is because of URLTransport, which is special). All stages rely on this default logic and abstract out the decision for whether that policy can handle an error to the `on(error:...)` method. The default is, nope they can't, and it just continues along the failure path.

But the presence of `on(error:...)` allows the policy author to attempt to recover from an error without overriding `process(...)`, and while we may not have any policy that attempts to do that now, I see no harm in keeping it around, especially since the pattern was borrowed from other AzureCore implementations.

My gut tells me that as soon we try to implement retry policy, we'll find ourselves needing this (or having to override `process` in that policy). @bsiegel I suggest we take no action unless in conjunction with #356.

**Comment by bsiegel** [comment]
Okay, thanks for the clarification. I'm good with closing this issue for now.

**Comment by tjprescott** [comment]
I'm okay leaving it open until we do #356 and decide whether the refactor makes sense. Then again, I am also okay closing it :D
