### ISSUE TITLE
[BUG] Add AzureCommunication as a dependency to AzureCommunicationChat

### ISSUE THREAD

**Issue by sacheu** [Azure/azure-sdk-for-ios#590]
**Describe the bug**

Currently, in Package.swift, AzureCommunicationChat only depends on AzureCore. And AzureCommunication depends on Azure Core.  I think we can change  AzureCommunicationChat to depends on both Azure core and AzureCommunication.

So that when developer works on AzureCommunicationChat, they don't need to install 2 packages.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by bsiegel** [comment]
Would like some more info on this. Right now Chat has no dependency on anything in AzureCommunication. Is the plan to add dependencies on that library?

Additionally, even if there is a dependency chain Chat -> AzureCommunication -> AzureCore, since source files in Chat must `import AzureCore`, Chat should still declare AzureCore as a direct dependency.

Basically, there should be a 1:1 mapping from (1 or more `import Foo` statements in the source code for a library) -> direct dependency declared on Foo in the podspec / Package.swift.

**Comment by tjprescott** [comment]
@JoshuaLai  @knvsl this is done, yes?

**Comment by tjprescott** [comment]
This has been fixed.
