### ISSUE TITLE
XCFramework support for AzureCommunicationCalling.

### ISSUE THREAD

**Issue by raosanat** [Azure/azure-sdk-for-ios#732]
**Is your feature request related to a problem? Please describe.**
We need to support XCFramework with CocoaPods for AzureCommunicationCalling.

**Describe the solution you'd like**
Using CocoaPods we need to support:

1. Existing FAT framework created using lipo for customers using XCode versions below 12 as there is no support for XCframework support there.
2. Customers using XCode 12.3 and above and 14.4 iOS version need the XCFramework as FAT frameworks won't work here.

We can either have 2 pod specs or one podspecs that works with both kind of frameworks. Proper approach needs to be investigated.

**Describe alternatives you've considered**
Nothing as of now.

**Additional context**
As XCode 12.3 and above existing FAT framework created using lipo wont work.
https://blog.embrace.io/xcode-12-and-xcframework/

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by raosanat** [comment]
XCode 11 does support xcframework. Maybe if none of the customers are below XCode 11 we could just switch completely over to XCFramework. But we dont have enough information about that so first release we might want to support both and before we GA we can just switch over completely to xcframework.

**Comment by smartcat32** [comment]
Last weekend I tried to create an XCFramework (in Xcode 12.3) that simply wraps all four ACS frameworks (beta 8, pulled down via CocoaPods). It failed to build due to AzureCommunicationCalling not able to find AzureCommunication/AzureCommunication-Swift.h (file not found).  

I wanted an XCFramework so I could stick ACS into a Swift package of my own (for distributing my ACS-based functionality to the app teams in my company).  There are only two ways a Swift package can contain ACS: either the ACS modules have an SPM, or they have an XCFramework.  

Here's my podfile:
```
platform :ios, '13.0'

#source 'https://github.com/Azure/azure-sdk-for-ios.git'

target 'ACS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AzureCallDemo  
  pod 'AzureCommunicationChat', '~> 1.0.0-beta.8'
  pod 'AzureCommunicationCalling', '~> 1.0.0-beta.8'
  pod 'AzureCommunication', '~> 1.0.0-beta.8'
  pod 'AzureCore', '~> 1.0.0-beta.8'

end
```
In my framework project (named ACS), I had created a single .swift file that imports AzureCommunicationCalling, AzureCommunicationChat, AzureCommunication, and AzureCore.  I created a single class that had a single method that simply called CallClient().  I don't know if this Swift file is even needed but it shouldn't hurt any.  

Here's the command I used for trying to build the XCFramework: 
```
xcodebuild archive -scheme ACS -destination "generic/platform=iOS" -archivePath ../output/ACS SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
```

I'd really like to know if Azure team is committed to providing an SPM or XCFramework for AzureCommunicationCalling beofre they ship 1.0, so my company can make a sound integration strategy. Requiring Xcode 12.3+ sounds reasonable to me.

If anyone (Azure Team or anyone else) wants to discuss this in a chat, I can be found on [ios-developers](https://ios-developers.io) Slack as "smartcat".  Feel free to DM me there (am PST timezone).  If you have ideas for how to create an XCFramework for AzureCommunicationCalling, I'd love to chat.

**Comment by raosanat** [comment]
Hi @smartcat32 thanks for the question. Yes we are working actively to support XCFramework and Swift PM. We have made a release of `AzureCommunicationCalling` SDK with XCFramework support [here](Azure Communication Calling iOS SDK version 1.0.0-beta.9). Since `AzureCommunication` and `AzureCore` are built from source with Swift PM support coming soon you will be able to fetch `AzureCommunicationCalling` as XCFramework binary and build `AzureCommunication` and `AzureCore` from source. 
There was a known limitation with Swift PM with support of Objective-C binary frameworks to be fetched using Swift PM. But we will re-visit that and update here as it looks like the Swift PM now supports this.

**Comment by smartcat32** [comment]
Thanks, @raosanat but I think there's still a problem with AzureCommunicationCalling beta 9's XCFramework.  Its public header AzureCommunicationCalling.framework/Headers/AzureCommunicationCalling.h has line 6 that imports <AzureCommunication/AzureCommunication-Swift.h>.   This file can't be found as there is no AzureCommunication headers exposed publically from this XCFramework.  

I'm trying to create a package that depends upon AzureCommunicationCalling and AzureCommunicationChat.  And therefore I think the package also needs to directly depend upon AzureCommunication and AzureCore as well.  

When I bring my package into an Xcode app project via SPM and then try to build the app, I get "Could not build Objective-C module 'AzureCommunicationCalling' and it's due to the above-mentioned AzureCommunication-Swift.h file not found. (BTW I've tried both Xcode 12.3 and 12.4).

I've even tried creating another target in my Package.swift, called AzureCommunicationCallingTarget, that names as a dependenzy both AzureCommunication and AzureCommunicationCalling (the binary target).  Then used this target in my package target as a dependency (rather than AzureCommunicationCalling directly).  This didn't work either, as now my source files in the package can't find AzureCommuicationCalling as an import.  

Can you provide an example Package.swift that works for you?

**Comment by tjprescott** [comment]
Hi @smartcat32 we were hoping beta 9 would be ready for SPM but we ran into the same issues as you. We are working on this branch https://github.com/Azure/azure-sdk-for-ios/pull/760 to explore what further changes are needed to support this scenario.

**Comment by tjprescott** [comment]
AzureCommunicationCalling is using XCFrameworks, so I will close this issue.
